actual_steps: 40
args_file: ckpts_af3/af3_1022_RandP_tr_only/args.yaml
atom_max_neighbors: 8
atom_radius: 5
batch_size: 4
c_alpha_max_neighbors: 10
cache_path: ''
checkpoint_path: null
config_file: config/rna.yaml
cross_cutoff_bias: 40
cross_cutoff_weight: 3
cross_dist_embed_dim: 32
cross_max_dist: 80
data_file: /home/fr/fr_fr/fr_ma453/DiffDock-PP/data_af3/af3_1022P_1022R.csv
data_path: /gpfs/bwfor/work/ws/fr_ma453-data_alpha_fold/dill_all
dataset: rna
debug: false
dist_embed_dim: 32
distributed: false
dropout: 0.0
dynamic_max_cross: true
ebd_type: continuous
embedding_scale: 10000
embedding_type: sinusoidal
encoder_type: e3nn
energy_loss_weight: 1.0
entity: null
epochs: 2000
filtering_model_path: null
generate_n_predictions: 7
gpu: 0
group: null
hidden_size: 64
knn_size: 30
lm_embed_dim: 640
log_file: ckpts_af3/af3_1022_RandP_tr_only/results.yaml
log_frequency: 10
logger: wandb
lr: 0.001
matching_maxiter: 20
matching_popsize: 20
max_lig_size: null
max_poses: 100
max_radius: 5.0
metric: loss
mirror_ligand: false
mode: train
model_type: e3nn
multiplicity: 1
no_batch_norm: true
no_final_noise: false
no_graph_cache: false
no_lm_cache: false
no_random: false
no_rotation: false
no_torsion: true
no_tqdm: false
ns: 16
num_conv_layers: 4
num_folds: 1
num_gpu: 1
num_inference_complexes: null
num_inference_complexes_train_data: 14
num_samples: null
num_steps: 40
num_workers: 0
nv: 4
ode: false
original_model: false
patience: 50
pose_path: data
prediction_storage: false
project: DiffDock Tuning
recache: true
receptor_radius: 30
remove_hs: false
resolution: residue
rmsd_classification_cutoff: 5
rmsd_prediction: false
rna_model path: /home/fr/fr_fr/fr_ma453/DiffDock-PP/RNA-FM_pretrained.pth
rna_model_path: null
rot_s_max: 1.65
rot_s_min: 0.01
rot_weight: 0.75
rotation: false
run_inference_without_confidence_model: false
run_name: af3_1022_RandP_tr_only
sample_train: true
samples_directory: ''
save_model_every: 10
save_path: ckpts_af3/af3_1022_RandP_tr_only
save_pred: false
scale_by_sigma: true
score_loss_weight: 0.0
score_model_path: null
seed: 0
sigma_embed_dim: 32
temp_psi: 0.0
temp_sampling: 1.0
temp_sigma_data_rot: 0.5
temp_sigma_data_tr: 0.5
tensorboard_path: runs
test_fold: 0
tor_s_max: 3.14
tor_s_min: 0.0314
tor_weight: 0.0
torchhub_path: torchhub
tr_s_max: 30.0
tr_s_min: 0.01
tr_weight: 0.25
translation: false
tuned_param: ''
use_complex_rmsd: false
use_interface_rmsd: false
use_orientation_features: false
use_randomized_confidence_data: false
use_second_order_repr: false
use_unbound: false
val_inference_freq: 10
visualization_path: visualization/af3_1022_RandP_tr_only
visualize_n_val_graphs: 5
wandb_run_name: null
wandb_sweep: false
weight_decay: 0.0
translation: true
rotation: false 
torsion: false